### ISSUE TITLE
Repository empty?

### ISSUE THREAD

**Issue by LlewellynJones** [elastic/elasticsearch-net-example#12]
I cloned this repository but it seems to be empty. No projects, no source code?

**Comment by christofur** [comment]
Hey @LlewellynJones, did you try switching to a different branch? (such as `5.x`)

**Comment by russcam** [comment]
Hey @LlewellynJones, as @christofur suggests, you'll want to check out one of the version branches:

- `5.x.` : starting 5.x branch
- `5.x-codecomplete`: finished 5.x branch
- `2.x` : starting 2.x branch
- `2.x-codecomplete`: finished 2.x branch

once you've cloned it, run

```
git checkout 5.x
```

and you'll be good to start 😄
