### ISSUE TITLE
Missing code in 5.x README.md

### ISSUE THREAD

**Issue by christofur** [elastic/elasticsearch-net-example#13]
`README.md` in `5.x` contains the line:

> Now we just need to make a small change to IndexDumps() and have it call GetPackages() instead of reading from Dumps directly by changing line 1 to:

< missing code here >

The correct line of code should be:

```csharp
var packages = DumpReader.GetPackages();
```

**Comment by christofur** [comment]
Fix in PR: https://github.com/elastic/elasticsearch-net-example/pull/14

**Comment by Mpdreamz** [comment]
F
