### ISSUE TITLE
I can't download nuget-data.zip

### ISSUE THREAD

**Issue by cldroddl** [elastic/elasticsearch-net-example#16]
I read README.md.
but I can't download nuget-data.zip.
I want to exercise elasticsearch-net. 
I need nuget-data.zip.
Help me please.

**Comment by christofur** [comment]
Hey @cldroddl 

Here's the direct link (works for me): https://nusearch.blob.core.windows.net/dump/nuget-data-dec-2016.zip 

Does this link allow you to download the zip?

**Comment by Mpdreamz** [comment]
Thanks @christofur for the direct link.

Just checked and all the links in all the branches still resolve for me. Let us know if this is still an issue @cldroddl

**Comment by cldroddl** [comment]
Thank you for @christofur , @Mpdreamz .
Let me know this problem is caused my office network.
I taked the zip file.
Thank you.
