### ISSUE TITLE
Elasticsearch NEST tutorial times out after long processing

### ISSUE THREAD

**Issue by sramalingam24** [elastic/elasticsearch-net-example#22]
Following along the tutorial here
https://github.com/elastic/elasticsearch-net-example/tree/5.x with elasticsearch 5.6 and changing the code as below i get response timed out exception on windows 7. All the settings are default and cluster is running on localhost:9200

```
static void IndexDumps()
{
 	   var packages = DumpReader.Dumps.Select(s=>s.NugetPackages);

            var result = Client.IndexMany(packages);

            if (!result.IsValid)
            {
                Console.WriteLine(result.OriginalException.ToString());
            }            

            Console.WriteLine("Done.");
}
```
Also when using the BulkAll call I modified FeedPackage to contain the entire text of each xml file and nothing else, the size parameter seems to have a threshold after which the BulkAll call fails with OOM and/or timeout errors. So is there a way to let NEST optimize this parameter based on file size, number etc...?
Thanks

**Comment by russcam** [comment]
@sramalingam24 changing the code to try to index _all_ nuget packages in _one_ bulk request is likely not going to work and you'll get a response time out as you're seeing. The combined byte size of all packages is too large for one request, so you need to split them up into several bulk requests as the tutorial does.

> Also when using the BulkAll call I modified FeedPackage to contain the entire text of each xml file and nothing else, the size parameter seems to have a threshold after which the BulkAll call fails with OOM and/or timeout errors. 

You are free to play clone/fork the example and play around with it, but making any changes to the content presented therein is left as an exercise. Generally, when sending more bigger documents (as in more bytes per document), you need to lower the size parameter. How much you'll need to lower it is going to depend on many environmental factors, including the hardware on which you are running Elasticsearch.

> So is there a way to let NEST optimize this parameter based on file size, number etc...?

No there isn't, for similar reasons as above; the amount of documents and ultimately bytes that you can send in one request and concurrently to an Elasticsearch cluster depends on many factors, including hardware, cluster usage ( indexing / search / etc ratio ), etc.
