### ISSUE TITLE
Outdated URL in 5.x Branch.

### ISSUE THREAD

**Issue by Icey88** [elastic/elasticsearch-net-example#23]
Readme in branch 5.x is out of date in regards to source data URL, I've not compared anything else as I've not progressed past downloading the source data. Tried pushing changes, but ofc don't have access.

`-Make sure you change `c:\nuget-data` to where you extracted the [nuget data dump](http://esdotnet.blob.core.windows.net/nusearch/nuget-data.zip)
+Make sure you change `c:\nuget-data` to where you extracted the [nuget data dump](https://nusearch.blob.core.windows.net/dump/nuget-data-jul-2017.zip).
`

Attached is the modified file.

[README.md.zip](https://github.com/elastic/elasticsearch-net-example/files/1397566/README.md.zip)

**Comment by russcam** [comment]
@Icey88  thanks. Would you like to [submit a Pull Request](https://github.com/elastic/elasticsearch-net-example/pulls) with the change?

**Comment by Icey88** [comment]
Done. :)

https://github.com/elastic/elasticsearch-net-example/pull/24

**Comment by codebrain** [comment]
Merged PR and closed this issue.
