### ISSUE TITLE
The aliasing doesn't seem to work as expected in the example

### ISSUE THREAD

**Issue by sramalingam24** [elastic/elasticsearch-net-example#25]
On a Windows 10 machine with local Elasticsearch 6.0
If i run the example twice in a row with the given data the alias still seems to point to the old index as opposed to the new index

![image](https://user-images.githubusercontent.com/10510152/34588798-88dff4bc-f174-11e7-8cc2-284974dad8ed.png)

![image](https://user-images.githubusercontent.com/10510152/34588890-0a0255c6-f175-11e7-8dc5-6f66693d62e1.png)

**Comment by russcam** [comment]
The example has not been updated to work with Elasticsearch 6.0 yet. Could you try again, running it against Elasticsearch 5.x?

**Comment by sramalingam24** [comment]
Yeah that works, thanks!
