### ISSUE TITLE
Is there any v6.x sample i missed ? WhiteApp console for Custom JsonSerializer

### ISSUE THREAD

**Issue by tebeco** [elastic/elasticsearch-net-example#27]
I was looking for a sample about Custome Json Serializer explained here
https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/custom-serialization.html#custom-serialization

Explanation there are fine but i was looking for a more complex sample to see if i havent missed something
It could also be used as a kind of "White app" so that anyone willing to work on their own Serializer could fork / edit / test the sample

**Comment by russcam** [comment]
Hey @tebeco, there's no 6.x sample of this repository yet; any help to

1. upgrade to 6.x
2. move to .NET Core 2.1

would be most awesome 😄 

The best place to look at a custom serializer at the moment would be the [`JsonNetSerializer`](https://github.com/elastic/elasticsearch-net/blob/master/src/Serializers/Nest.JsonNetSerializer/JsonNetSerializer.cs). It's a custom serializer that uses Json.NET to perform serialization of your documents, handing back to the internal serializer for types defined in NEST that may be defined on your document type e.g. `QueryContainer` on a document used for percolation.

**Comment by tebeco** [comment]
thx for the info
