### ISSUE TITLE
nuget-data

### ISSUE THREAD

**Issue by wjkhappy14** [elastic/elasticsearch-net-example#28]
public static string PackagePath => 
			RuntimeInformation.IsOSPlatform(OSPlatform.Windows) ? @"C:\nuget-data" : "/nuget-data";

how to get nuget data ?

**Comment by wjkhappy14** [comment]
https://github.com/elastic/elasticsearch-net-example/tree/6.x-codecomplete-netcore

**Comment by wjkhappy14** [comment]
https://github.com/elastic/elasticsearch-net-example/tree/6.x-codecomplete-netcore

**Comment by wjkhappy14** [comment]
http://nusear.ch/

**Comment by wjkhappy14** [comment]
https://nusearch.blob.core.windows.net/dump/nuget-data-jul-2017.zip

**Comment by russcam** [comment]
The last link is the correct one. Closing this.

**Comment by cuongdo926** [comment]
The link is dead. Please update the link. Thank you
