### ISSUE TITLE
How does the IXXXRequest API work?

### ISSUE THREAD

**Issue by haf-afa** [elastic/elasticsearch-net-example#32]
![es-client-strange-api](https://user-images.githubusercontent.com/56340843/68300552-4cb53c00-009e-11ea-81f0-ecf9bad1fc46.PNG)

What do I return from the builder methods? Docs are completely outdated or non-existent here.

**Comment by russcam** [comment]
> What do I return from the builder methods?

Descriptors _explicitly_ implement the interface, and each method call returns the descriptor instance. In C# and VB.Net, you don't need to return anything, but in F# you would need to cast the descriptor to the interface. For this reason, you may want to use the _object initializer_ syntax, as opposed to the _fluent_ syntax. For example, the fluent syntax would be

```f#
let index (i:string) = IndexName.op_Implicit i

let createIndexResponse = client.Indices.Create(index "kubernetes-resources", fun c ->
    c.Map<Honey>(fun m -> m.AutoMap() :> ITypeMapping) :> ICreateIndexRequest
)
```

and the _object initializer_ syntax

```f#
let index (i:string) = IndexName.op_Implicit i

let createIndexRequest = new CreateIndexRequest(index "kubernetes-resources")
let walker = new PropertyWalker(typedefof<Honey>, null, 0)
let properties = walker.GetProperties()
let mapping = new TypeMapping()
mapping.Properties <- properties
createIndexRequest.Mappings <- mapping

let createIndexResponse = client.Indices.Create(createIndexRequest)
```

> Docs are completely outdated or non-existent here.

We don't have docs in F#, but we do have [up to date docs in C# for mapping](https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/mapping.html)

**Comment by haf-afa** [comment]
Thank you!
