### ISSUE TITLE
.Net core 3 bug.

### ISSUE THREAD

**Issue by john-jay** [elastic/elasticsearch-net-example#36]
The 7.x branch works well, except I had to remove UseKestrel from the Web Program.cs.

Error: "Application is running inside IIS process but is not configured to use IIS server."
Fix in line 16: 		            webBuilder // .UseKestrel()

**Comment by russcam** [comment]
Thanks @john-jay, I've fixed this in f8d5395 for 7.x and 7.x-codecomplete.
