### ISSUE TITLE
7.x client.index does not work

### ISSUE THREAD

**Issue by subiect** [elastic/elasticsearch-net-example#37]
I try to follow the tutorial in 7.x branch but I cannot.
After replacing IndexDumps() with the code provided I get

Error	CS0411	The type arguments for method 'ElasticClient.Index<TDocument>(IIndexRequest<TDocument>)' cannot be inferred from the usage. Try specifying the type arguments explicitly.	NuSearch.Indexer

**Comment by russcam** [comment]
Fixed in 6ca80af
