### ISSUE TITLE
update this to NEST 2

### ISSUE THREAD

**Issue by cbmdk** [elastic/elasticsearch-net-example#5]
Hey,

This example is not working anymore, when hitting the Client.Index(package); it errors out.

Could you please update the example to the newest version of NEST.

thanks in advance :)

/Chr

**Comment by russcam** [comment]
@cbmdk Take a look in the [codecomplete-2.x branch](https://github.com/elastic/elasticsearch-net-example/tree/codecomplete-2.x); this should be up to date against the latest NEST 2.x packages. It's on the task list to be merged into master :smile:

**Comment by cbmdk** [comment]
awesome!

**Comment by russcam** [comment]
Latest commit looks like 2.1.1 - give me 2 minutes and I'll update to 2.3.2

**Comment by russcam** [comment]
Done :smile:

**Comment by Mpdreamz** [comment]
https://github.com/elastic/elasticsearch-net-example/tree/2.x

Is now the canonical `2.x` branch, will update master to just be a single readme pointing to appropiate branches
