### ISSUE TITLE
Problems with operator "=>"

### ISSUE THREAD

**Issue by cesar2** [elastic/elasticsearch-net-example#9]
Hi! I am new with ES with NEST, and I am trying to follow your tutorial. But when I download it, I have some problems with some lines, almost all have the "=>" operator, like:

In NugetDumpReader.cs:
```
public IEnumerable<NugetDump> Dumps => this._files.Select(this.EagerlyReadDump);
public IEnumerable<FeedPackage> Packages => this._files.SelectMany(this.LazilyReadDumps);
```

And in NuSearchConfiguration.cs:
```
return $"{LiveIndexAlias}-{DateTime.UtcNow:dd-MM-yyyy-HH-mm-ss}";
```

Do you know why? Thanks!!

**Comment by gmarz** [comment]
These are new constructs in [C# 6.0](https://msdn.microsoft.com/en-us/magazine/dn802602.aspx), so you must be on an older version.

If upgrading isn't an option, then you can simply substitute the interpolated string with `string.Format`:

```csharp
return string.Format("{0}-{1}, LiveIndexAlias, DateTime.UtcNow:dd-MM-yyyy-HH-mm-ss);
```

and the expression bodied properties with

```csharp
public IEnumerable<FeedPackage> Packages()
{
    return this._files.SelectMany(this.LazilyReadDumps);
}
```

Hope it helps :)
